### ISSUE TITLE
BLAST usage errors as of BLAST+ 2.10

### ISSUE THREAD

**Issue by tillea** [paulstothard/cgview_comparison_tool#5]
Hi,
please consider to apply this [patch](https://salsa.debian.org/med-team/cct/-/blob/master/debian/patches/conditionalize_blast_-Q_-D.patch) that was tested for Debian with the latest version of BLAST.
Kind regards, Andreas.

**Comment by naphtap** [comment]
Hello,
In which command would I apply the patch?

Thank you

**Comment by tillea** [comment]
Just do

    patch -p1 < patchfile

**Comment by paulstothard** [comment]
Thank you for the patch. I've modified the relevant script so that the legacy blastall command's -Q and -D flags are only supplied to BLAST variants that involve translating queries and subjects respectively.
