### ISSUE TITLE
PERL FAILURE

### ISSUE THREAD

**Issue by vappiah** [paulstothard/cgview_comparison_tool#6]
I tried using cgview and it failed. the check_env was successful, however when I used on my data (prokka generated genbank files), I get this error 

I tried using cgview and it failed. the check_env was successful, however when I used on my data (prokka generated genbank files), I get this error 

Performing BLAST search for sequence number 8653 (rfaY;S4_09114;_start=9364892;end=9365317;strand=-1;rf=3).
Writing HSP to file.
Open salmonella_project/cct_projects/S4/blast/blast_results_local/S4_CDS_vs_S9.gbk_cds_CDS_blastp to view the BLAST results.
[Wednesday April 07 08:01:05 2021] [Notice] The BLAST results have been written to salmonella_project/cct_projects/S4/blast/blast_results_local.
[Wednesday April 07 08:01:05 2021] [Notice] Assigning COG categories to CDS translations from reference genome sequence in salmonella_project/cct_projects/S4/reference_genome.
Cannot open file : No such file or directory at /home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/assign_cogs/assign_cogs.pl line 223.
The following command failed: perl /home/yser/apps/bioinfo/cgview_comparison_tool/lib/scripts/assign_cogs/assign_cogs.pl -i 'salmonella_project/cct_projects/S4/reference_genome/S4.gbk' -o 'salmonella_project/cct_projects/S4/features/S4.gbk_cds_cogs.gff' -s 'cds' -myva '/home/user/apps/bioinfo/cgview_comparison_tool/cog_db/myva' -whog '/home/user/apps/bioinfo/cgview_comparison_tool/cog_db/whog' -get_orfs '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/get_orfs/get_orfs.pl' -get_cds '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/get_cds/get_cds.pl' -local_bl '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/local_blast_client/local_blast_client.pl' -blastall 'blastall' -c '11' -e '0.1' -starts 'ttg|ctg|att|atc|ata|atg|gtg' -stops 'taa|tag|tga' -m_orf '25' -m_score '0'.
The following command failed: perl /home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/assign_cogs/assign_cogs.pl -i 'salmonella_project/cct_projects/S4/reference_genome/S4.gbk' -o 'salmonella_project/cct_projects/S4/features/S4.gbk_cds_cogs.gff' -s 'cds' -myva '/home/user/apps/bioinfo/cgview_comparison_tool/cog_db/myva' -whog '/home/user/apps/bioinfo/cgview_comparison_tool/cog_db/whog' -get_orfs '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/get_orfs/get_orfs.pl' -get_cds '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/get_cds/get_cds.pl' -local_bl '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/local_blast_client/local_blast_client.pl' -blastall 'blastall' -c '11' -e '0.1' -starts 'ttg|ctg|att|atc|ata|atg|gtg' -stops 'taa|tag|tga' -m_orf '25' -m_score '0'. at /home/user/apps/bioinfo/cgview_comparison_tool/scripts/cgview_comparison_tool.pl line 891.
	main::_assignCogs(HASH(0x560e9260b7c8), Util::LogManager=HASH(0x560e925750c0)) called at /home/user/apps/bioinfo/cgview_comparison_tool/scripts/cgview_comparison_tool.pl line 799
	main::_sequenceAnalysis(HASH(0x560e921513e8), Util::Configurator=HASH(0x560e925a08a8), Util::LogManager=HASH(0x560e925750c0)) called at /home/user/apps/bioinfo/cgview_comparison_tool/scripts/cgview_comparison_tool.pl line 103

[Wednesday April 07 08:01:46 2021] [Error] The following command failed: perl /home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/assign_cogs/assign_cogs.pl -i 'salmonella_project/cct_projects/S4/reference_genome/S4.gbk' -o 'salmonella_project/cct_projects/S4/features/S4.gbk_cds_cogs.gff' -s 'cds' -myva '/home/user/apps/bioinfo/cgview_comparison_tool/cog_db/myva' -whog '/home/user/apps/bioinfo/cgview_comparison_tool/cog_db/whog' -get_orfs '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/get_orfs/get_orfs.pl' -get_cds '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/get_cds/get_cds.pl' -local_bl '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/local_blast_client/local_blast_client.pl' -blastall 'blastall' -c '11' -e '0.1' -starts 'ttg|ctg|att|atc|ata|atg|gtg' -stops 'taa|tag|tga' -m_orf '25' -m_score '0'.

[Wednesday April 07 08:01:46 2021] [Error] The following command failed: perl /home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/assign_cogs/assign_cogs.pl -i 'salmonella_project/cct_projects/S4/reference_genome/S4.gbk' -o 'salmonella_project/cct_projects/S4/features/S4.gbk_cds_cogs.gff' -s 'cds' -myva '/home/user/apps/bioinfo/cgview_comparison_tool/cog_db/myva' -whog '/home/user/apps/bioinfo/cgview_comparison_tool/cog_db/whog' -get_orfs '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/get_orfs/get_orfs.pl' -get_cds '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/get_cds/get_cds.pl' -local_bl '/home/user/apps/bioinfo/cgview_comparison_tool/lib/scripts/local_blast_client/local_blast_client.pl' -blastall 'blastall' -c '11' -e '0.1' -starts 'ttg|ctg|att|atc|ata|atg|gtg' -stops 'taa|tag|tga' -m_orf '25' -m_score '0'. at /home/user/apps/bioinfo/cgview_comparison_tool/scripts/cgview_comparison_tool.pl line 891.
	main::_assignCogs(HASH(0x560e9260b7c8), Util::LogManager=HASH(0x560e925750c0)) called at /home/user/apps/bioinfo/cgview_comparison_tool/scripts/cgview_comparison_tool.pl line 799
	main::_sequenceAnalysis(HASH(0x560e921513e8), Util::Configurator=HASH(0x560e925a08a8), Util::LogManager=HASH(0x560e925750c0)) called at /home/user/apps/bioinfo/cgview_comparison_tool/scripts/cgview_comparison_tool.pl line 103

**Comment by paulstothard** [comment]
Hello,

Please run the `build_cog_db.sh` script, located in the `cgview_comparison_tool/scripts` directory:

```bash
./build_cog_db.sh
```

This should fix the issue.

Paul

**Comment by vappiah** [comment]
Thanks . After running the script, it works now
