### ISSUE TITLE
Multipe genome comparision not being done

### ISSUE THREAD

**Issue by dikshyantg** [paulstothard/cgview_comparison_tool#7]
I have tried to run cgview on multiple genome by putting those multiple genome into comaprison_genomes folder, however I always get the comparison done vs the first genome file not with the others.  I have three genomes .gbk files in that folder as shown in the image bu the comparision is being done with just one of them. 

<img width="512" alt="Screen Shot 2021-04-12 at 8 46 44 AM" src="https://user-images.githubusercontent.com/46819356/114404877-bbd47100-9b6b-11eb-9bca-4d287bbbef8b.png">

**Comment by paulstothard** [comment]
I suspect that the two files that aren't processed have issues with the feature table or are missing CDS features, but I'm not certain. If you provide one or both files I will look into the issue further.

**Comment by dikshyantg** [comment]
I checked it a while ago and the issue was with the gbk files. Thanks!
