### ISSUE TITLE
gbff with multiple contigs a issue?

### ISSUE THREAD

**Issue by dikshyantg** [paulstothard/cgview_comparison_tool#8]
I have this gbff file downloaded from NCBI and it has around 511 contigs , Is this the reason the CGC fails to give me a mapping against this gbff file?
[GCF_000238775.1_ASM23877v2_genomic.txt](https://github.com/paulstothard/cgview_comparison_tool/files/6344839/GCF_000238775.1_ASM23877v2_genomic.txt)

**Comment by paulstothard** [comment]
The file will work but the program expects a `.gbk` file extension. The following commands worked for me:

```bash
mv GCF_000238775.1_ASM23877v2_genomic.txt test.gbk
docker pull pstothard/cgview_comparison_tool
docker run --rm -v "$(pwd)":/dir -w /dir pstothard/cgview_comparison_tool build_blast_atlas.sh -i test.gbk 
docker run --rm -v "$(pwd)":/dir -w /dir pstothard/cgview_comparison_tool build_blast_atlas.sh -p test 
```
