### ISSUE TITLE
genome with plasmids vs genome with plasmids

### ISSUE THREAD

**Issue by dikshyantg** [paulstothard/cgview_comparison_tool#9]
One of my genome with plasmids with extension .gb ran through docker gave accurate representation of size another one I downloaded from NCBI which had a genome with around 6503724 bp and 9 other plasmids with different sizes. When I draw a map of this later genome I only get map of 6503724 bp , without addition of 9 other plasmids. They are all in one single files.  The file was too big so I took a snapshot for the image. The gbk file has been uploaded by converting it to text as gbk format is not supported
[NC_009925.1.txt](https://github.com/paulstothard/cgview_comparison_tool/files/6346167/NC_009925.1.txt)

<img width="989" alt="Screen Shot 2021-04-20 at 2 21 41 PM" src="https://user-images.githubusercontent.com/46819356/115452352-f0879e80-a1e3-11eb-865c-fd3f2de81cee.png">

**Comment by paulstothard** [comment]
The program considers the plasmids distinct natural molecules and so you would need to process each individually as a separate reference genome.
